# Generated by Django 4.2.4 on 2023-08-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('type', models.CharField(choices=[('melt', 'melt'), ('sandwich', 'sandwich')], max_length=8)),
            ],
        ),
    ]
