# Generated by Django 4.2.4 on 2023-08-28 01:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0003_alter_staff_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('type', models.CharField(choices=[('melt', 'melt'), ('sandwich', 'sandwich'), ('drink', 'drink'), ('crisp', 'crisp')], max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='12345', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='12345', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
