# Generated by Django 4.2.4 on 2023-08-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0004_menuitems_delete_items_staff_password_users_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
