# Generated by Django 4.2.4 on 2023-08-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0006_rename_name_users_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
