# Generated by Django 4.2.4 on 2023-09-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0007_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='picture',
            field=models.ImageField(null=True, upload_to='items_pic/'),
        ),
    ]
