# Generated by Django 4.2.4 on 2023-09-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurent', '0008_delete_staff_menuitems_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='info',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
